name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        type: string
        description: The name of the workspace to deploy to
        required: true
        default: 'Workshop - Lab 2'
      environment:
        type: choice
        description: The environment to deploy to
        required: true
        default: 'DEV'
        options:
        - DEV
        - PRD
  
env:
  environment_name: ${{ github.event.inputs.environment || 'PRD' }}
  workspace_name: ${{ github.event.inputs.workspace || vars.workspace || 'Workshop - Lab 2' }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'PRD' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install fabric-cicd
        run: |
          python -m pip install fabric-cicd

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Run Deployment Script 
        run: >
          python scripts/deploy.py
          --spn-auth True
          --workspace_name "$workspace_name"
          --environment "$environment_name"          
